<?xml version="1.0" encoding="UTF-8"?>
<!-- 
stylesheet to prepare an HTRC MODS 3.x document (single record) for transformation to HTRC MODS RDF
by Colleen Fallaw, HathiTrust Research Center

HT-0.10	10-16-2014	CF	initial version 
-->
<!-- precondition: a single mods record xml document with a mods root element as generated by HathiTrust's
	 HTRC_MARC21slim2MODS3-4.xsl  https://github.com/wcsa/HTRCMARC2RDF/blob/master/HTRC_MARC21slim2MODS3-4.xsl   -->
<!-- postcondition: a valid mods record xml document that can be consumed by HathiTrust's
	 HTRC-modsrdf.xsl https://github.com/wcsa/HTRCMARC2RDF/blob/master/HTRC-modsrdf.xsl   -->
	 

<xsl:stylesheet version="2.0" xmlns="http://www.loc.gov/mods/v3"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<!-- use xsl identity with exception pattern to add modsIdentifier element and remove unneeded recordInfo element-->
	<xsl:template match="@*|node()">
		<xsl:copy>
			<xsl:apply-templates select="@*|node()"/>
		</xsl:copy>
	</xsl:template>
	<xsl:template match="*:recordInfo">
		<identifier type="modsIdentifier">http://catalog.htrc.illinois.edu/bibent/<xsl:value-of
				select="//*:recordInfo/*:recordIdentifier[@source='MiAaHDL']"/></identifier>
	</xsl:template>

</xsl:stylesheet>
